PLUGIN_NAME=        reticulum
PLUGIN_VERSION=     1.0
PLUGIN_REVISION=    0
PLUGIN_COMMENT=     Reticulum Network Stack and LXMF Propagation Node
PLUGIN_MAINTAINER=  ops@reticulum.network
PLUGIN_WWW=         https://reticulum.network
PLUGIN_DEPENDS=     python311 py311-cryptography py311-setuptools py311-wheel

.include "../../Mk/plugins.mk"
