PLUGIN_NAME=		reticulum
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Reticulum Network Stack - Transport & Propagation Node
PLUGIN_DEPENDS=		py311-rns py311-lxmf
PLUGIN_MAINTAINER=	maintainer@example.org
PLUGIN_WWW=		https://reticulum.network/
PLUGIN_CATEGORIES=	net
PLUGIN_TIER=		2

.include "../Mk/plugins.mk"
