[start.rnsd]
command:service rnsd start
type:script
message:Starting Reticulum rnsd

[stop.rnsd]
command:service rnsd stop
type:script
message:Stopping Reticulum rnsd

[restart.rnsd]
command:service rnsd restart
type:script
message:Restarting Reticulum rnsd

[status.rnsd]
command:/usr/local/opnsense/scripts/OPNsense/Reticulum/rnsd_status.sh
type:script_output
message:Checking rnsd status

[start.lxmd]
command:service lxmd start
type:script
message:Starting LXMF lxmd

[stop.lxmd]
command:service lxmd stop
type:script
message:Stopping LXMF lxmd

[restart.lxmd]
command:service lxmd restart
type:script
message:Restarting LXMF lxmd

[status.lxmd]
command:/usr/local/opnsense/scripts/OPNsense/Reticulum/lxmd_status.sh
type:script_output
message:Checking lxmd status

[reconfigure]
command:/usr/local/opnsense/scripts/OPNsense/Reticulum/reconfigure.sh
type:script
message:Reconfiguring Reticulum services

[rnstatus]
command:/usr/local/opnsense/scripts/OPNsense/Reticulum/rnstatus.sh
type:script_output
message:Fetching Reticulum network status

[info]
command:/usr/local/opnsense/scripts/OPNsense/Reticulum/info.sh
type:script_output
message:Fetching Reticulum version info

[logs.rnsd]
command:tail -n %s /var/log/reticulum/rnsd.log
type:script_output
message:Fetching rnsd logs
parameters:%s

[logs.lxmd]
command:tail -n %s /var/log/reticulum/lxmd.log
type:script_output
message:Fetching lxmd logs
parameters:%s
