# logfilename                          [owner:group]  mode  count  size  when  flags
/var/log/reticulum/rnsd.log            reticulum:reticulum  640  5  10240  *  C
/var/log/reticulum/lxmd.log            reticulum:reticulum  640  5  10240  *  C
